const PDFDocument = require('pdfkit');
const fs = require('fs');

const generatePDF = (record, filePath) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 40, size: 'A4' });
            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Header
            doc.rect(0, 0, doc.page.width, 120).fill('#050505');
            doc.fontSize(24).fillColor('#00E5FF').text('ATTENDANCE REPORT', 40, 30, { align: 'center' });
            doc.fontSize(10).fillColor('#00FFFF').text('University Student Attendance Checker', { align: 'center' });
            doc.fontSize(8).fillColor('#AAAAAA').text(`Generated on ${new Date().toLocaleString()}`, { align: 'center' });

            doc.moveDown(3);

            // Student Info
            doc.fontSize(14).fillColor('#00E5FF').text('Student Information');
            doc.moveDown(0.5);
            doc.fontSize(10).fillColor('#333333');

            const info = [
                ['Name', record.student.name],
                ['Roll Number', record.student.rollNumber],
                ['Year', `${record.student.year}`],
                ['Department', record.student.department],
                ['Semester', record.student.semester],
                ['Email', record.student.email],
                ['Phone', record.student.phone]
            ];

            info.forEach(([label, value]) => {
                doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
                doc.font('Helvetica').text(value);
            });

            doc.moveDown(1);

            // Attendance Table Header
            doc.fontSize(14).fillColor('#00E5FF').text('Subject-wise Attendance');
            doc.moveDown(0.5);

            const tableTop = doc.y;
            const tableHeaders = ['Subject', 'Faculty', 'Attended', 'Total', '%', 'Needed', 'Status'];
            const colWidths = [110, 90, 55, 45, 50, 50, 55];
            let x = 40;

            // Table header
            doc.rect(x, tableTop, 515, 20).fill('#111111');
            doc.fontSize(8).fillColor('#00E5FF');
            tableHeaders.forEach((header, i) => {
                doc.text(header, x + 5, tableTop + 5, { width: colWidths[i], align: 'left' });
                x += colWidths[i];
            });

            // Table rows
            let y = tableTop + 22;
            record.subjects.forEach((subject, index) => {
                if (y > 700) {
                    doc.addPage();
                    y = 40;
                }

                const bgColor = index % 2 === 0 ? '#FAFAFA' : '#F0F0F0';
                doc.rect(40, y, 515, 18).fill(bgColor);

                x = 40;
                doc.fontSize(7).fillColor('#333333');
                const rowData = [
                    subject.subjectName,
                    subject.facultyName,
                    `${subject.attendedClasses}`,
                    `${subject.totalClasses}`,
                    `${subject.percentage}%`,
                    `${subject.classesNeeded}`,
                    subject.status
                ];

                rowData.forEach((data, i) => {
                    const color = i === 6 ? (data === 'PASS' ? '#00AA55' : '#FF1744') : '#333333';
                    doc.fillColor(color).text(data, x + 5, y + 5, { width: colWidths[i], align: 'left' });
                    x += colWidths[i];
                });

                y += 20;
            });

            // Overall stats
            y += 15;
            doc.rect(40, y, 515, 60).fill('#111111').stroke('#00E5FF');

            doc.fontSize(12).fillColor('#00E5FF').text('OVERALL RESULT', 50, y + 8);
            doc.fontSize(10).fillColor('#FFFFFF');
            doc.text(`Total Classes: ${record.overallAttendance.totalClasses}`, 50, y + 25);
            doc.text(`Attended: ${record.overallAttendance.totalAttended}`, 200, y + 25);
            doc.text(`Percentage: ${record.overallAttendance.percentage}%`, 350, y + 25);

            const statusColor = record.overallAttendance.status === 'PASS' ? '#00FF7F' : '#FF1744';
            doc.fontSize(14).fillColor(statusColor).text(
                `STATUS: ${record.overallAttendance.status}`,
                50, y + 42,
                { align: 'center' }
            );

            // Footer
            const footerY = doc.page.height - 40;
            doc.fontSize(7).fillColor('#999999').text(
                'This report was generated by University Student Attendance Checker | © 2024',
                40, footerY, { align: 'center', width: 515 }
            );

            doc.end();
            stream.on('finish', resolve);
            stream.on('error', reject);
        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generatePDF };
